name: GitHub Actions Test

on:
  push:
    branches:
      - main  # Runs the action when changes are pushed to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 23f2001318@ds.study.iitm.ac.in
        run: echo "Hello, world!"
